# Generated by Django 3.2.9 on 2021-12-21 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsInPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True, max_length=140, null=True)),
                ('comment_date', models.CharField(max_length=25)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.post')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
