# Generated by Django 3.2.8 on 2022-01-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211229_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followingandfollowers',
            name='subscribed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
